"""Geographic constants — STATES_DATA, STATE_CENTERS, DISTRICT_COORDINATES, BLOCK_COORDINATES,
LINEAR_KEYWORDS, TITLE_TEMPLATES, SECTOR_WEIGHTS."""

import numpy as np
from typing import Dict, List

LINEAR_KEYWORDS = [
    # Roads
    "road", "highway", "expressway", "bypass", "four-lan", "bituminous", "resurfac",
    "widening", "ring road", "service road", "pmgsy",
    # Bridges
    "bridge", "flyover", "over-bridge", "over bridge", " rob ", "underpass",
    # Linear utilities
    "pipeline", "canal", "drain", "drainage", "sewage line", "sewer",
    "fibre", "ofc", "bharatnet",
    "transmission line", "power line", "11kv", "33kv",
    # Linear transport
    "metro corridor", "railway track", "track doubling",
]

STATES_DATA: Dict[str, Dict[str, List[str]]] = {
    "Uttar Pradesh": {
        "Lucknow":    ["Sarojini Nagar", "Alambagh", "Chinhat", "Malihabad"],
        "Agra":       ["Tajganj", "Fatehabad", "Kiraoli", "Bah"],
        "Varanasi":   ["Kashi Vidyapeeth", "Arajiline", "Rohania", "Chiraigaon"],
        "Kanpur":     ["Nawabganj", "Kalyanpur", "Bilhaur", "Ghatampur"],
        "Prayagraj":  ["Phulpur", "Meja", "Soraon", "Handia"],
        "Gorakhpur":  ["Sahjanwa", "Campierganj", "Gola", "Khajni"],
    },
    "Maharashtra": {
        "Mumbai":     ["Worli", "Andheri East", "Borivali", "Kurla"],
        "Pune":       ["Hadapsar", "Kothrud", "Pimpri", "Bhor"],
        "Nagpur":     ["Butibori", "Kamptee", "Hingna", "Ramtek"],
        "Nashik":     ["Panchavati", "Satpur", "Igatpuri", "Sinnar"],
        "Aurangabad": ["Waluj", "Garkheda", "Phulambri", "Kannad"],
        "Solapur":    ["South Solapur", "Akkalkot", "Pandharpur", "Mohol"],
    },
    "Rajasthan": {
        "Jaipur":  ["Sanganer", "Amber", "Chaksu", "Jamwa Ramgarh"],
        "Jodhpur": ["Bilara", "Bhopalgarh", "Luni", "Mandore"],
        "Udaipur": ["Girwa", "Vallabhnagar", "Kherwara", "Salumbar"],
        "Kota":    ["Ladpura", "Ramganj Mandi", "Pipalda", "Baran"],
        "Ajmer":   ["Pisangan", "Masuda", "Kekri", "Nasirabad"],
        "Bikaner": ["Lunkaransar", "Kolayat", "Nokha", "Bajju"],
    },
    "Madhya Pradesh": {
        "Bhopal":   ["Huzur", "Berasia", "Phanda", "Sehore"],
        "Indore":   ["Rajendra Nagar", "Sanwer", "Depalpur", "Mhow"],
        "Jabalpur": ["Panagar", "Shahpura", "Sihora", "Kundam"],
        "Gwalior":  ["Morar", "Dabra", "Bhitarwar", "Murar"],
        "Rewa":     ["Rewa Urban", "Mauganj", "Sirmaur", "Teonthar"],
    },
    "Bihar": {
        "Patna":       ["Patliputra", "Phulwari Sharif", "Danapur", "Masaurhi"],
        "Samastipur":  ["Kalyanpur", "Rosera", "Patori", "Dalsinghsarai", "Warisnagar", "Singhia"],
        "Muzaffarpur": ["Motipur", "Kanti", "Sakra", "Aurai"],
        "Gaya":        ["Bodhgaya", "Sherghati", "Manpur", "Amas"],
        "Bhagalpur":   ["Naugachia", "Sultanganj", "Kahalgaon", "Banka"],
        "Darbhanga":   ["Bahera", "Keoti", "Jale", "Singhwara"],
    },
    "Karnataka": {
        "Bangalore Urban": ["Whitefield", "Yelahanka", "Bommanahalli", "Dasarahalli"],
        "Mysore":          ["Hunsur", "Krishnarajanagara", "Nanjangud", "Periyapatna"],
        "Hubli-Dharwad":   ["Dharwad", "Hubli", "Kundgol", "Kalghatgi"],
        "Belagavi":        ["Belagavi City", "Chikkodi", "Gokak", "Hukkeri"],
        "Mangaluru":       ["Bantwal", "Belthangady", "Puttur", "Sullia"],
    },
    "Tamil Nadu": {
        "Chennai":     ["Sholinganallur", "Ambattur", "Thiruvottiyur", "Alandur"],
        "Coimbatore":  ["Peelamedu", "Pollachi", "Annur", "Kinathukadavu"],
        "Madurai":     ["Anna Nagar", "Melur", "Thiruparankundram", "Usilampatti"],
        "Salem":       ["Edappadi", "Sankari", "Attur", "Mettur"],
        "Tirunelveli": ["Palayamkottai", "Ambasamudram", "Nanguneri", "Radhapuram"],
    },
    "West Bengal": {
        "Kolkata":     ["Salt Lake", "Jadavpur", "Behala", "Dum Dum"],
        "Howrah":      ["Shibpur", "Uluberia", "Amta", "Bagnan"],
        "Burdwan":     ["Durgapur", "Asansol", "Kalna", "Katwa"],
        "Darjeeling":  ["Siliguri", "Kurseong", "Kalimpong", "Mirik"],
        "Murshidabad": ["Berhampore", "Lalbagh", "Jangipur", "Kandi"],
    },
    "Gujarat": {
        "Ahmedabad":   ["Naranpura", "Bopal", "Chandkheda", "Nikol"],
        "Surat":       ["Vesu", "Adajan", "Varachha", "Olpad"],
        "Rajkot":      ["Aji Dam", "Gondal", "Jetpur", "Upleta"],
        "Vadodara":    ["Ajwa", "Waghodiya", "Padra", "Savli"],
        "Gandhinagar": ["Mansa", "Dehgam", "Kalol", "Gandhinagar Urban"],
    },
    "Andhra Pradesh": {
        "Visakhapatnam": ["Gajuwaka", "Bheemunipatnam", "Padmanabham", "Anakapalle"],
        "Guntur":        ["Amaravati", "Tenali", "Narasaraopet", "Sattenapalle"],
        "Kurnool":       ["Nandyal", "Adoni", "Yemmiganur", "Alur"],
        "Chittoor":      ["Renigunta", "Tirupati Urban", "Madanapalle", "Palamaner"],
    },
    "Telangana": {
        "Hyderabad": ["Patancheru", "LB Nagar", "Secunderabad", "Kukatpally"],
        "Warangal":  ["Kazipet", "Hanamkonda", "Narsampet", "Mahabubabad"],
        "Khammam":   ["Khammam Urban", "Kothagudem", "Yellandu", "Bhadrachalam"],
        "Nizamabad": ["Dichpally", "Bodhan", "Armur", "Banswada"],
    },
    "Odisha": {
        "Khurda":     ["Bhubaneswar", "Jatni", "Balianta", "Chilika"],
        "Cuttack":    ["Cuttack City", "Athagarh", "Banki", "Tigiria"],
        "Sundargarh": ["Rourkela", "Bonai", "Rajgangpur", "Hemgir"],
        "Puri":       ["Puri Urban", "Konark", "Pipili", "Astaranga"],
    },
    "Punjab": {
        "Ludhiana":  ["Sahnewal", "Raikot", "Samrala", "Khanna"],
        "Amritsar":  ["Golden Temple", "Ajnala", "Baba Bakala", "Lopoke"],
        "Patiala":   ["Urban Estate", "Rajpura", "Nabha", "Samana"],
        "Jalandhar": ["Nakodar", "Phillaur", "Shahkot", "Bhogpur"],
    },
    "Haryana": {
        "Gurugram":  ["DLF Phase 1", "Sohna", "Pataudi", "Farrukhnagar"],
        "Faridabad": ["Sector 21C", "Ballabhgarh", "Palwal", "Hodal"],
        "Hisar":     ["Hisar Urban", "Hansi", "Barwala", "Fatehabad"],
        "Ambala":    ["Ambala City", "Naraingarh", "Shahzadpur", "Mulana"],
    },
    "Delhi": {
        "South Delhi": ["Safdarjung", "Vasant Kunj", "Mehrauli", "Hauz Khas"],
        "North Delhi": ["Civil Lines", "Alipur", "Burari", "Timarpur"],
        "East Delhi":  ["Mayur Vihar", "Laxmi Nagar", "Shahdara", "Gandhi Nagar"],
        "West Delhi":  ["Dwarka Sector 21", "Palam", "Janakpuri", "Uttam Nagar"],
    },
    "Jharkhand": {
        "Ranchi":         ["Namkum", "Ormanjhi", "Kanke", "Ratu"],
        "Dhanbad":        ["Jharia", "Sindri", "Nirsa", "Baghmara"],
        "East Singhbhum": ["Jugsalai", "Boram", "Potka", "Baharagora"],
        "Hazaribagh":     ["Barhi", "Churchu", "Padma", "Chalkusa"],
    },
    "Assam": {
        "Kamrup Metro": ["Dispur", "Guwahati East", "Jalukbari", "Hengrabari"],
        "Dibrugarh":    ["Dibrugarh East", "Duliajan", "Lahowal", "Khowang"],
        "Cachar":       ["Silchar", "Sonai", "Udharbond", "Lakhipur"],
        "Nagaon":       ["Nagaon Town", "Raha", "Lumding", "Hojai"],
    },
    "Chhattisgarh": {
        "Raipur":   ["Avanti Vihar", "Abhanpur", "Arang", "Tilda"],
        "Bilaspur": ["Masturi", "Takhatpur", "Mungeli", "Lormi"],
        "Durg":     ["Bhilai", "Patan", "Berla", "Durg Urban"],
        "Bastar":   ["Jagdalpur", "Kondagaon", "Bijapur", "Narayanpur"],
    },
    "Himachal Pradesh": {
        "Shimla": ["Mashobra", "Chopal", "Rampur", "Rohru"],
        "Kullu":  ["Manali", "Banjar", "Ani", "Nirmand"],
        "Kangra": ["Dharamshala", "Nurpur", "Palampur", "Dehra"],
    },
    "Uttarakhand": {
        "Dehradun":    ["Raipur", "Vikasnagar", "Chakrata", "Tyuni"],
        "Haridwar":    ["Har ki Pauri", "Roorkee", "Manglaur", "Laksar"],
        "Rudraprayag": ["Ukhimath", "Augustmuni", "Jakholi", "Kedarnath"],
        "Nainital":    ["Haldwani", "Ramnagar", "Bhimtal", "Okhalkanda"],
    },
    "Kerala": {
        "Ernakulam":          ["Fort Kochi", "Aluva", "Muvattupuzha", "Kothamangalam"],
        "Thiruvananthapuram": ["Kazhakuttam", "Varkala", "Attingal", "Nedumangad"],
        "Kozhikode":          ["Beypore", "Vadakara", "Koyilandy", "Balussery"],
        "Thrissur":           ["Thrissur Urban", "Chalakudy", "Kodungallur", "Chavakkad"],
    },
    "Goa": {
        "North Goa": ["Panaji", "Mapusa", "Pernem", "Bicholim"],
        "South Goa": ["Margao", "Vasco", "Ponda", "Sanguem"],
    },
    "Jammu & Kashmir": {
        "Jammu":    ["Bhalwal", "Akhnoor", "Nagrota", "Marh"],
        "Srinagar": ["Lal Chowk", "Hazratbal", "Shalteng", "Pantha Chowk"],
        "Anantnag": ["Pahalgam", "Kokernag", "Dooru", "Bijbehara"],
        "Baramulla": ["Sopore", "Pattan", "Uri", "Rafiabad"],
    },
    "Tripura": {
        "West Tripura": ["Agartala", "Majlishpur", "Mandai", "Hezamara"],
        "Gomati":       ["Udaipur", "Amarpur", "Karbook", "Kakraban"],
    },
    "Meghalaya": {
        "East Khasi Hills": ["Shillong", "Mawkyrwat", "Pynursla", "Mairang"],
        "Ri Bhoi":          ["Nongpoh", "Umsning", "Bhoirymbong", "Jirang"],
    },
    "Arunachal Pradesh": {
        "Itanagar Capital Complex": ["Naharlagun", "Banderdewa", "Nirjuli", "Doimukh"],
        "East Siang":               ["Pasighat", "Mebo", "Nari", "Ruksin"],
        "West Kameng":              ["Bomdila", "Dirang", "Kalaktang", "Rupa"],
    },
    "Manipur": {
        "Imphal West": ["Lamphelpat", "Patsoi", "Wangoi", "Nambol"],
        "Imphal East": ["Porompat", "Heingang", "Jiribam", "Lamlai"],
        "Thoubal":     ["Thoubal Town", "Kakching", "Wangjing", "Khangabok"],
        "Bishnupur":   ["Bishnupur Town", "Moirang", "Oinam", "Phougakchao"],
    },
    "Mizoram": {
        "Aizawl":   ["Aizawl North", "Aizawl South", "Tlangnuam", "Darlawn"],
        "Lunglei":  ["Lunglei Town", "Hnahthial", "Bunghmun", "Lawngtlai"],
        "Champhai": ["Champhai Town", "Khawzawl", "Ngopa", "Suangpuilawn"],
    },
    "Nagaland": {
        "Kohima":     ["Kohima Town", "Jakhama", "Viswema", "Tsiesema"],
        "Dimapur":    ["Dimapur Town", "Chumukedima", "Niuland", "Medziphema"],
        "Mokokchung": ["Mokokchung Town", "Longkhum", "Tuli", "Changtongya"],
    },
    "Sikkim": {
        "East Sikkim":  ["Gangtok", "Ranka", "Pakyong", "Rongli"],
        "West Sikkim":  ["Gyalshing", "Soreng", "Dentam", "Kaluk"],
        "North Sikkim": ["Mangan", "Chungthang", "Lachen", "Lachung"],
        "South Sikkim": ["Namchi", "Ravangla", "Jorethang", "Melli"],
    },
}

STATE_CENTERS: Dict[str, Dict[str, float]] = {
    "Uttar Pradesh":     {"lat": 26.85,  "lon": 80.91,  "zoom": 6},
    "Maharashtra":       {"lat": 19.75,  "lon": 75.71,  "zoom": 6},
    "Rajasthan":         {"lat": 27.02,  "lon": 74.22,  "zoom": 6},
    "Madhya Pradesh":    {"lat": 22.97,  "lon": 78.65,  "zoom": 6},
    "Bihar":             {"lat": 25.09,  "lon": 85.31,  "zoom": 7},
    "Karnataka":         {"lat": 15.31,  "lon": 75.71,  "zoom": 6},
    "Tamil Nadu":        {"lat": 11.12,  "lon": 78.66,  "zoom": 6},
    "West Bengal":       {"lat": 22.98,  "lon": 87.85,  "zoom": 7},
    "Gujarat":           {"lat": 22.26,  "lon": 71.19,  "zoom": 6},
    "Andhra Pradesh":    {"lat": 15.91,  "lon": 79.74,  "zoom": 6},
    "Telangana":         {"lat": 17.12,  "lon": 79.02,  "zoom": 7},
    "Odisha":            {"lat": 20.94,  "lon": 84.80,  "zoom": 7},
    "Punjab":            {"lat": 31.15,  "lon": 75.34,  "zoom": 7},
    "Haryana":           {"lat": 29.06,  "lon": 76.08,  "zoom": 7},
    "Delhi":             {"lat": 28.66,  "lon": 77.21,  "zoom": 10},
    "Jharkhand":         {"lat": 23.61,  "lon": 85.27,  "zoom": 7},
    "Assam":             {"lat": 26.20,  "lon": 92.94,  "zoom": 7},
    "Chhattisgarh":      {"lat": 21.27,  "lon": 81.86,  "zoom": 7},
    "Himachal Pradesh":  {"lat": 31.10,  "lon": 77.17,  "zoom": 7},
    "Uttarakhand":       {"lat": 30.07,  "lon": 79.07,  "zoom": 7},
    "Kerala":            {"lat": 10.85,  "lon": 76.27,  "zoom": 7},
    "Goa":               {"lat": 15.30,  "lon": 74.12,  "zoom": 9},
    "Jammu & Kashmir":   {"lat": 33.73,  "lon": 76.92,  "zoom": 7},
    "Tripura":           {"lat": 23.94,  "lon": 91.99,  "zoom": 8},
    "Meghalaya":         {"lat": 25.47,  "lon": 91.37,  "zoom": 8},
    "Arunachal Pradesh": {"lat": 28.21,  "lon": 94.73,  "zoom": 7},
    "Manipur":           {"lat": 24.66,  "lon": 93.91,  "zoom": 8},
    "Mizoram":           {"lat": 23.16,  "lon": 92.94,  "zoom": 8},
    "Nagaland":          {"lat": 26.15,  "lon": 94.56,  "zoom": 8},
    "Sikkim":            {"lat": 27.53,  "lon": 88.51,  "zoom": 8},
    # UTs with NIC portals
    "Puducherry":        {"lat": 11.94,  "lon": 79.81,  "zoom": 10},
    "Ladakh":            {"lat": 34.23,  "lon": 77.59,  "zoom": 7},
    "Chandigarh":        {"lat": 30.73,  "lon": 76.78,  "zoom": 11},
}

DISTRICT_COORDINATES: Dict[str, Dict[str, Dict[str, float]]] = {
    "Uttar Pradesh": {
        "Lucknow":            {"lat": 26.8467, "lon": 80.9462},
        "Agra":               {"lat": 27.1767, "lon": 78.0081},
        "Varanasi":           {"lat": 25.3176, "lon": 82.9739},
        "Kanpur":             {"lat": 26.4499, "lon": 80.3319},
        "Kanpur Nagar":       {"lat": 26.4499, "lon": 80.3319},
        "Prayagraj":          {"lat": 25.4358, "lon": 81.8463},
        "Gorakhpur":          {"lat": 26.7606, "lon": 83.3732},
        "Aligarh":            {"lat": 27.8974, "lon": 78.0880},
        "Mathura":            {"lat": 27.4924, "lon": 77.6737},
        "Meerut":             {"lat": 28.9845, "lon": 77.7064},
        "Ghaziabad":          {"lat": 28.6692, "lon": 77.4538},
        "Noida":              {"lat": 28.5355, "lon": 77.3910},
        "Gautam Buddha Nagar":{"lat": 28.5355, "lon": 77.3910},
        "Bareilly":           {"lat": 28.3670, "lon": 79.4304},
        "Moradabad":          {"lat": 28.8386, "lon": 78.7733},
        "Saharanpur":         {"lat": 29.9679, "lon": 77.5460},
        "Muzaffarnagar":      {"lat": 29.4706, "lon": 77.7085},
        "Jhansi":             {"lat": 25.4484, "lon": 78.5685},
        "Gwalior":            {"lat": 26.2183, "lon": 78.1828},
        "Firozabad":          {"lat": 27.1519, "lon": 78.3957},
        "Shahjahanpur":       {"lat": 27.8817, "lon": 79.9049},
        "Lakhimpur Kheri":    {"lat": 27.9467, "lon": 80.7770},
        "Sitapur":            {"lat": 27.5677, "lon": 80.6867},
        "Hardoi":             {"lat": 27.3958, "lon": 80.1330},
        "Rae Bareli":         {"lat": 26.2237, "lon": 81.2375},
        "Sultanpur":          {"lat": 26.2601, "lon": 82.0727},
        "Ayodhya":            {"lat": 26.7947, "lon": 82.1858},
        "Gonda":              {"lat": 27.1342, "lon": 81.9590},
        "Bahraich":           {"lat": 27.5744, "lon": 81.5940},
        "Balrampur":          {"lat": 27.4251, "lon": 82.1791},
        "Shrawasti":          {"lat": 27.7187, "lon": 81.8665},
        "Basti":              {"lat": 26.8028, "lon": 82.7273},
        "Sant Kabir Nagar":   {"lat": 26.7827, "lon": 83.0593},
        "Siddharth Nagar":    {"lat": 27.2858, "lon": 83.0719},
        "Maharajganj":        {"lat": 27.1419, "lon": 83.5741},
        "Kushinagar":         {"lat": 26.7409, "lon": 83.8891},
        "Deoria":             {"lat": 26.5032, "lon": 83.7799},
        "Mau":                {"lat": 25.9426, "lon": 83.5610},
        "Azamgarh":           {"lat": 26.0684, "lon": 83.1836},
        "Ballia":             {"lat": 25.7578, "lon": 84.1478},
        "Ghazipur":           {"lat": 25.5794, "lon": 83.5730},
        "Chandauli":          {"lat": 25.2633, "lon": 83.2693},
        "Mirzapur":           {"lat": 25.1459, "lon": 82.5694},
        "Sonbhadra":          {"lat": 24.6804, "lon": 82.8884},
        "Allahabad":          {"lat": 25.4358, "lon": 81.8463},
        "Kaushambi":          {"lat": 25.5391, "lon": 81.3861},
        "Fatehpur":           {"lat": 25.9302, "lon": 80.8143},
        "Pratapgarh":         {"lat": 25.9015, "lon": 81.9947},
        "Jaunpur":            {"lat": 25.7463, "lon": 82.6836},
        "Unnao":              {"lat": 26.5449, "lon": 80.4867},
        "Etawah":             {"lat": 26.7799, "lon": 79.0170},
        "Farrukhabad":        {"lat": 27.3903, "lon": 79.5758},
        "Kannauj":            {"lat": 27.0599, "lon": 79.9210},
        "Mainpuri":           {"lat": 27.2373, "lon": 79.0226},
        "Etah":               {"lat": 27.5596, "lon": 78.6671},
        "Hathras":            {"lat": 27.5961, "lon": 78.0527},
        "Bulandshahr":        {"lat": 28.4066, "lon": 77.8565},
        "Baghpat":            {"lat": 28.9479, "lon": 77.2145},
        "Bagpat":             {"lat": 28.9479, "lon": 77.2145},
        "Bijnor":             {"lat": 29.3726, "lon": 78.1355},
        "Amroha":             {"lat": 28.9043, "lon": 78.4680},
        "Rampur":             {"lat": 28.7999, "lon": 79.0064},
        "Pilibhit":           {"lat": 28.6412, "lon": 79.8040},
        "Budaun":             {"lat": 28.0430, "lon": 79.1276},
        "Sambhal":            {"lat": 28.5904, "lon": 78.5688},
        "Auraiya":            {"lat": 26.4611, "lon": 79.5083},
        "Jalaun":             {"lat": 26.1426, "lon": 79.3297},
        "Hamirpur":           {"lat": 25.9443, "lon": 80.1489},
        "Mahoba":             {"lat": 25.2943, "lon": 79.8741},
        "Banda":              {"lat": 25.4762, "lon": 80.3345},
        "Chitrakoot":         {"lat": 25.1924, "lon": 80.8998},
        "Lalitpur":           {"lat": 24.6904, "lon": 78.4196},
        "Ambedkar Nagar":     {"lat": 26.4302, "lon": 82.6961},
        "Barabanki":          {"lat": 26.9237, "lon": 81.2018},
        "Shamli":             {"lat": 29.4498, "lon": 77.3180},
        "Hapur":              {"lat": 28.7310, "lon": 77.7762},
        "Sant Ravidas Nagar": {"lat": 25.3867, "lon": 82.5683},
        "Kanpur Dehat":       {"lat": 26.5031, "lon": 80.0022},
    },
    "Maharashtra": {
        "Mumbai":     {"lat": 19.0760, "lon": 72.8777},
        "Pune":       {"lat": 18.5204, "lon": 73.8567},
        "Nagpur":     {"lat": 21.1458, "lon": 79.0882},
        "Nashik":     {"lat": 20.0060, "lon": 73.7908},
        "Aurangabad": {"lat": 19.8762, "lon": 75.3433},
        "Solapur":    {"lat": 17.6599, "lon": 75.9064},
    },
    "Rajasthan": {
        "Jaipur":  {"lat": 26.9124, "lon": 75.7873},
        "Jodhpur": {"lat": 26.2389, "lon": 73.0243},
        "Udaipur": {"lat": 24.5854, "lon": 73.7125},
        "Kota":    {"lat": 25.2138, "lon": 75.8648},
        "Ajmer":   {"lat": 26.4499, "lon": 74.6399},
        "Bikaner": {"lat": 28.0229, "lon": 73.3119},
    },
    "Madhya Pradesh": {
        "Bhopal":   {"lat": 23.2599, "lon": 77.4126},
        "Indore":   {"lat": 22.7196, "lon": 75.8577},
        "Jabalpur": {"lat": 23.1815, "lon": 79.9864},
        "Gwalior":  {"lat": 26.2183, "lon": 78.1828},
        "Rewa":     {"lat": 24.5325, "lon": 81.3023},
    },
    "Bihar": {
        "Patna":       {"lat": 25.5941, "lon": 85.1376},
        "Samastipur":  {"lat": 25.8624, "lon": 85.7810},
        "Muzaffarpur": {"lat": 26.1197, "lon": 85.3910},
        "Gaya":        {"lat": 24.7960, "lon": 84.9994},
        "Bhagalpur":   {"lat": 25.2425, "lon": 86.9842},
        "Darbhanga":   {"lat": 26.1542, "lon": 85.8918},
    },
    "Karnataka": {
        "Bangalore Urban": {"lat": 12.9716, "lon": 77.5946},
        "Mysore":          {"lat": 12.2958, "lon": 76.6394},
        "Hubli-Dharwad":   {"lat": 15.3647, "lon": 75.1240},
        "Belagavi":        {"lat": 15.8497, "lon": 74.4977},
        "Mangaluru":       {"lat": 12.9141, "lon": 74.8560},
    },
    "Tamil Nadu": {
        "Chennai":     {"lat": 13.0827, "lon": 80.2707},
        "Coimbatore":  {"lat": 11.0168, "lon": 76.9558},
        "Madurai":     {"lat":  9.9252, "lon": 78.1198},
        "Salem":       {"lat": 11.6643, "lon": 78.1460},
        "Tirunelveli": {"lat":  8.7139, "lon": 77.7567},
    },
    "West Bengal": {
        "Kolkata":     {"lat": 22.5726, "lon": 88.3639},
        "Howrah":      {"lat": 22.5840, "lon": 88.3423},
        "Burdwan":     {"lat": 23.2324, "lon": 87.8615},
        "Darjeeling":  {"lat": 27.0410, "lon": 88.2663},
        "Murshidabad": {"lat": 24.1830, "lon": 88.2710},
    },
    "Gujarat": {
        "Ahmedabad":   {"lat": 23.0225, "lon": 72.5714},
        "Surat":       {"lat": 21.1702, "lon": 72.8311},
        "Rajkot":      {"lat": 22.3039, "lon": 70.8022},
        "Vadodara":    {"lat": 22.3072, "lon": 73.1812},
        "Gandhinagar": {"lat": 23.2156, "lon": 72.6369},
    },
    "Andhra Pradesh": {
        "Visakhapatnam": {"lat": 17.6868, "lon": 83.2185},
        "Guntur":        {"lat": 16.3067, "lon": 80.4365},
        "Kurnool":       {"lat": 15.8281, "lon": 78.0373},
        "Chittoor":      {"lat": 13.2172, "lon": 79.1003},
    },
    "Telangana": {
        "Hyderabad": {"lat": 17.3850, "lon": 78.4867},
        "Warangal":  {"lat": 17.9784, "lon": 79.5941},
        "Khammam":   {"lat": 17.2473, "lon": 80.1514},
        "Nizamabad": {"lat": 18.6725, "lon": 78.0941},
    },
    "Odisha": {
        "Khurda":     {"lat": 20.1812, "lon": 85.6195},
        "Cuttack":    {"lat": 20.4625, "lon": 85.8830},
        "Sundargarh": {"lat": 22.1217, "lon": 84.0297},
        "Puri":       {"lat": 19.8135, "lon": 85.8312},
    },
    "Punjab": {
        "Ludhiana":  {"lat": 30.9010, "lon": 75.8573},
        "Amritsar":  {"lat": 31.6340, "lon": 74.8723},
        "Patiala":   {"lat": 30.3398, "lon": 76.3869},
        "Jalandhar": {"lat": 31.3260, "lon": 75.5762},
    },
    "Haryana": {
        "Gurugram":  {"lat": 28.4595, "lon": 77.0266},
        "Faridabad": {"lat": 28.4089, "lon": 77.3178},
        "Hisar":     {"lat": 29.1492, "lon": 75.7217},
        "Ambala":    {"lat": 30.3782, "lon": 76.7767},
    },
    "Delhi": {
        "South Delhi": {"lat": 28.5355, "lon": 77.2390},
        "North Delhi": {"lat": 28.7041, "lon": 77.2025},
        "East Delhi":  {"lat": 28.6358, "lon": 77.2965},
        "West Delhi":  {"lat": 28.6663, "lon": 77.0667},
    },
    "Jharkhand": {
        "Ranchi":          {"lat": 23.3441, "lon": 85.3096},
        "Dhanbad":         {"lat": 23.7957, "lon": 86.4304},
        "East Singhbhum":  {"lat": 22.8046, "lon": 86.2029},
        "Hazaribagh":      {"lat": 23.9925, "lon": 85.3637},
    },
    "Assam": {
        "Kamrup Metro": {"lat": 26.1445, "lon": 91.7362},
        "Dibrugarh":    {"lat": 27.4728, "lon": 94.9120},
        "Cachar":       {"lat": 24.8333, "lon": 92.7789},
        "Nagaon":       {"lat": 26.3460, "lon": 92.6837},
    },
    "Chhattisgarh": {
        "Raipur":   {"lat": 21.2514, "lon": 81.6296},
        "Bilaspur": {"lat": 22.0796, "lon": 82.1391},
        "Durg":     {"lat": 21.1898, "lon": 81.2849},
        "Bastar":   {"lat": 19.0748, "lon": 82.0144},
    },
    "Himachal Pradesh": {
        "Shimla": {"lat": 31.1048, "lon": 77.1734},
        "Kullu":  {"lat": 31.9580, "lon": 77.1095},
        "Kangra": {"lat": 32.0998, "lon": 76.2691},
    },
    "Uttarakhand": {
        "Dehradun":     {"lat": 30.3165, "lon": 78.0322},
        "Haridwar":     {"lat": 29.9457, "lon": 78.1642},
        "Rudraprayag":  {"lat": 30.2849, "lon": 78.9810},
        "Nainital":     {"lat": 29.3919, "lon": 79.4542},
    },
    "Kerala": {
        "Ernakulam":          {"lat":  9.9816, "lon": 76.2999},
        "Thiruvananthapuram": {"lat":  8.5241, "lon": 76.9366},
        "Kozhikode":          {"lat": 11.2588, "lon": 75.7804},
        "Thrissur":           {"lat": 10.5276, "lon": 76.2144},
    },
    "Goa": {
        "North Goa": {"lat": 15.4909, "lon": 73.8278},
        "South Goa": {"lat": 15.2993, "lon": 74.1240},
    },
    "Jammu & Kashmir": {
        "Jammu":     {"lat": 32.7266, "lon": 74.8570},
        "Srinagar":  {"lat": 34.0837, "lon": 74.7973},
        "Anantnag":  {"lat": 33.7311, "lon": 75.1487},
        "Baramulla": {"lat": 34.2014, "lon": 74.3436},
    },
    "Tripura": {
        "West Tripura": {"lat": 23.8315, "lon": 91.2868},
        "Gomati":       {"lat": 23.5380, "lon": 91.4843},
    },
    "Meghalaya": {
        "East Khasi Hills": {"lat": 25.5788, "lon": 91.8933},
        "Ri Bhoi":          {"lat": 25.9067, "lon": 91.8754},
    },
    "Arunachal Pradesh": {
        "Itanagar Capital Complex": {"lat": 27.0844, "lon": 93.6053},
        "East Siang":               {"lat": 28.0736, "lon": 95.3236},
        "West Kameng":              {"lat": 27.2641, "lon": 92.5401},
    },
    "Manipur": {
        "Imphal West": {"lat": 24.8170, "lon": 93.9368},
        "Imphal East": {"lat": 24.8074, "lon": 93.9987},
        "Thoubal":     {"lat": 24.6360, "lon": 93.9990},
        "Bishnupur":   {"lat": 24.6222, "lon": 93.7624},
    },
    "Mizoram": {
        "Aizawl":   {"lat": 23.7271, "lon": 92.7176},
        "Lunglei":  {"lat": 22.8882, "lon": 92.7348},
        "Champhai": {"lat": 23.4561, "lon": 93.3285},
    },
    "Nagaland": {
        "Kohima":     {"lat": 25.6751, "lon": 94.1086},
        "Dimapur":    {"lat": 25.9050, "lon": 93.7265},
        "Mokokchung": {"lat": 26.3284, "lon": 94.5138},
    },
    "Sikkim": {
        "East Sikkim":  {"lat": 27.3389, "lon": 88.6065},
        "West Sikkim":  {"lat": 27.2900, "lon": 88.2200},
        "North Sikkim": {"lat": 27.8500, "lon": 88.6000},
        "South Sikkim": {"lat": 27.1650, "lon": 88.2800},
    },
}

BLOCK_COORDINATES: Dict[str, Dict[str, Dict[str, Dict[str, float]]]] = {
    "Bihar": {
        "Samastipur": {
            "Kalyanpur":        {"lat": 25.9797, "lon": 85.7964},
            "Rosera":           {"lat": 25.7798, "lon": 86.0425},
            "Patori":           {"lat": 25.9300, "lon": 85.8600},
            "Dalsinghsarai":    {"lat": 25.6727, "lon": 85.8124},
            "Warisnagar":       {"lat": 25.9178, "lon": 85.8668},
            "Singhia":          {"lat": 25.8276, "lon": 86.1757},
        },
    },
}

TITLE_TEMPLATES: Dict[str, List[str]] = {
    "Infrastructure": [
        "Construction of {sector} Road in {block}, {district}",
        "Bridge over River near {block}, {district} District",
        "Four-Laning of State Highway through {district}",
        "Rehabilitation of NH Bypass at {block}",
        "Flyover Construction at {block} Junction, {district}",
        "Rural Road Connectivity Package — {block} Cluster",
        "Construction of Bypass Road for {district} Urban Area",
        "Grade Separator & Overpass at {block}, {district}",
    ],
    "Health": [
        "CHC Construction at {block}, {district}",
        "District Hospital Upgrade — {district}",
        "Primary Health Centre Renovation at {block}",
        "Medical Equipment Procurement for {district} Hospitals",
        "AYUSH Wellness Centre at {block}",
        "Cold Chain Infrastructure for NHM — {district}",
        "Ambulance Fleet Augmentation — {state}",
    ],
    "Education": [
        "Construction of Government School Building at {block}",
        "Smart Classroom Installation — {district} Schools",
        "College Infrastructure Development at {district}",
        "Hostel Block Construction — Navodaya Vidyalaya {district}",
        "Library & Lab Facility at {block}, {district}",
        "Digitisation of School Records — {district}",
        "Construction of Multi-Purpose Hall at {block} School",
        "Drinking Water & Sanitation Facility in {district} Schools",
    ],
    "Agriculture": [
        "Farm Pond Construction under PMKSY — {block}",
        "Cold Storage Warehouse at {district} Mandi",
        "Soil Testing Laboratory Setup at {block}",
        "Micro-Irrigation Network — {district} Cluster",
        "PM-KUSUM Solar Pump Installation — {block}",
        "Custom Hiring Centre for Farm Equipment — {block}",
        "Post-Harvest Processing Unit at {district}",
    ],
    "MSME": [
        "Common Facility Centre for {sector} Cluster — {district}",
        "MSME Industrial Shed Construction at {block}",
        "Technology Upgradation of Handloom Units — {district}",
        "Tool Room Modernisation — {district} MSME Hub",
        "Effluent Treatment Plant for Industrial Cluster at {block}",
        "Digital Marketplace Infrastructure for MSMEs — {state}",
    ],
    "Energy": [
        "Solar Power Plant (5 MW) at {block}, {district}",
        "Rural Electrification under DDUGJY — {block} Villages",
        "Substation Augmentation at {district}",
        "Smart Meter Rollout — {district} DISCOM",
        "Wind Energy Feasibility & Infrastructure — {district}",
        "Rooftop Solar Programme for Govt Buildings — {district}",
        "Transmission Line Upgradation — {block} Region",
    ],
    "Water & Sanitation": [
        "Jal Jeevan Mission — Piped Water Supply to {block}",
        "Overhead Tank Construction at {block}, {district}",
        "Sewage Treatment Plant Upgrade — {district}",
        "Solid Waste Management System — {block} ULB",
        "Open Defecation Free Village Programme — {block}",
        "River Front Development — {district}",
        "Deep Tubewell Installation for Drinking Water — {block}",
        "Effluent Channel Lining Project — {district}",
    ],
    "Urban Development": [
        "AMRUT 2.0 — Storm Water Drain Network at {district}",
        "PMAY Urban Housing Complex — {block}",
        "Metro Rail Infrastructure Extension — {district}",
        "Smart Road & Street Lighting — {block} Ward",
        "Parks & Public Spaces Development — {district}",
        "Integrated Command Control Centre — {district} Smart City",
        "Solid Waste Management Plant — {block} Municipality",
    ],
    "Rural Development": [
        "PMGSY Road Package — {block} Gram Panchayat Links",
        "PMAY Gramin Housing — {block} Phase II",
        "MNREGA Water Conservation Works — {district}",
        "Rural Community Centre at {block}",
        "Skill Development Centre — {block}, {district}",
        "Anganwadi Centre Construction — {block} Cluster",
        "Digital Village Initiative — {block}",
    ],
    "Minority Affairs": [
        "Minority Residential School at {district}",
        "Waqf Property Development — {district}",
        "Skill Training Centre for Minorities — {block}",
        "Scholarship & Hostel Infrastructure — {district}",
        "MSDP Community Hall at {block}",
    ],
    "Social Welfare": [
        "SC/ST Residential School Construction — {district}",
        "Anganwadi Strengthening Programme — {block}",
        "Women Safety & Empowerment Centre — {district}",
        "Tribal Development Hostel at {block}",
        "Senior Citizen Home Construction — {block}, {district}",
        "Divyang Rehabilitation Centre — {district}",
    ],
    "Digital & IT": [
        "BharatNet Optical Fibre Network — {block} GPs",
        "Common Service Centre Hub at {block}",
        "e-Governance Platform for {district} Administration",
        "Data Centre Infrastructure — {state} NIC",
        "CCTV Surveillance Network — {block} ULB",
        "Digital Literacy Centre at {block}",
        "Telecom Tower Installation — {block} Remote Areas",
    ],
}

SECTOR_WEIGHTS: np.ndarray = np.array([
    0.22,   # Infrastructure
    0.12,   # Health
    0.14,   # Education
    0.10,   # Agriculture
    0.06,   # MSME
    0.08,   # Energy
    0.11,   # Water & Sanitation
    0.08,   # Urban Development
    0.07,   # Rural Development
    0.02,   # Minority Affairs
    0.04,   # Social Welfare
    0.04,   # Digital & IT
], dtype=np.float64)

# Normalise to sum exactly to 1.0
SECTOR_WEIGHTS = SECTOR_WEIGHTS / SECTOR_WEIGHTS.sum()
