"""Sector constants — SECTOR_DEPARTMENTS and SECTOR_COLORS."""

from typing import Dict, List

SECTOR_DEPARTMENTS: Dict[str, List[str]] = {
    "Infrastructure": [
        "NHAI (National Highway Authority)",
        "CPWD (Central Public Works Dept)",
        "Border Roads Organisation (BRO)",
        "State PWD",
        "Smart Cities Mission",
        "Airport Authority of India",
        "Railways Infrastructure Div",
        "RRDA (Rural Road Dev Agency)",
    ],
    "Health": [
        "National Health Mission (NHM)",
        "Ministry of Health & Family Welfare",
        "AIIMS (All India Institute of Med Sci)",
        "CGHS",
        "Ayushman Bharat - PMJAY",
        "State Health Dept",
        "National AIDS Control Org",
    ],
    "Education": [
        "Samagra Shiksha Abhiyan",
        "Ministry of Education",
        "UGC (Univ Grants Commission)",
        "Navodaya Vidyalaya Samiti",
        "IIT / NIT Infrastructure",
        "State Education Dept",
        "CBSE School Infrastructure",
    ],
    "Agriculture": [
        "Ministry of Agriculture & Farmers Welfare",
        "ICAR (Research Infrastructure)",
        "FCI (Food Corporation of India)",
        "NABARD Rural Infrastructure",
        "State Agriculture Dept",
        "PM-KUSUM Solar Pump Scheme",
        "National Horticulture Board",
    ],
    "MSME": [
        "Ministry of MSME",
        "NSIC (National Small Industries Corp)",
        "SIDBI",
        "Khadi & Village Industries Commission",
        "State MSME Dept",
        "MSME Technology Centre",
    ],
    "Energy": [
        "NTPC Ltd",
        "SECI (Solar Energy Corp of India)",
        "Power Grid Corporation",
        "State DISCOM",
        "Ministry of New & Renewable Energy",
        "Rural Electrification Corp (REC)",
        "BHEL Infrastructure",
    ],
    "Water & Sanitation": [
        "Jal Jeevan Mission",
        "Swachh Bharat Mission (Urban)",
        "Swachh Bharat Mission (Rural)",
        "Central Water Commission",
        "State Irrigation Dept",
        "NMCG (Namami Gange)",
        "National Water Development Agency",
    ],
    "Urban Development": [
        "AMRUT 2.0",
        "PMAY - Urban Housing",
        "Smart Cities Mission",
        "Municipal Corporation",
        "State Housing Board",
        "Metro Rail Corporation",
        "DUDA (District Urban Dev Authority)",
    ],
    "Rural Development": [
        "PMGSY (Pradhan Mantri Gram Sadak Yojana)",
        "PMAY - Gramin",
        "MNREGA Infrastructure Works",
        "National Rural Livelihood Mission",
        "State Rural Dev Dept",
        "DRDA (Dist Rural Dev Agency)",
    ],
    "Minority Affairs": [
        "Ministry of Minority Affairs",
        "MSDP (Multi-Sector Dev Programme)",
        "Waqf Board Infrastructure",
        "State Minority Dev Corp",
        "National Minorities Dev & Finance Corp",
    ],
    "Social Welfare": [
        "Ministry of Social Justice & Empowerment",
        "Tribal Affairs Dept",
        "Women & Child Development",
        "Anganwadi Infrastructure Programme",
        "SC/ST Development Corp",
    ],
    "Digital & IT": [
        "MeitY (Ministry of Electronics & IT)",
        "BharatNet Phase-3",
        "Common Service Centre (CSC)",
        "NIC Infrastructure",
        "State IT Dept",
        "CDAC Infrastructure",
    ],
}

SECTOR_COLORS: Dict[str, str] = {
    "Infrastructure":     "#E74C3C",
    "Health":             "#3498DB",
    "Education":          "#9B59B6",
    "Agriculture":        "#27AE60",
    "MSME":               "#E67E22",
    "Energy":             "#F1C40F",
    "Water & Sanitation": "#1ABC9C",
    "Urban Development":  "#2C3E50",
    "Rural Development":  "#7F8C8D",
    "Minority Affairs":   "#D35400",
    "Social Welfare":     "#C0392B",
    "Digital & IT":       "#2980B9",
}
